---
resources:
  - './deployment-stable.yml'
  - './service-nodeports.yml'

configMapGenerator:
  - name: 'rails-env'
    literals:
      - 'RAILS_ENV=production'
      - 'RACK_ENV=production'
      - 'RAILS_SERVE_STATIC_FILES=1'
  - name: 'node-env'
    literals:
      - 'NODE_ENV=production'

secretGenerator:
  - name: 'secret-key-base'
    files:
      - './secret/SECRET_KEY_BASE'
  - name: 'twitter-consumer-secret'
    files:
      - './secret/TWITTER_CONSUMER_SECRET'
  - name: 'twitter-access-token-secret'
    files:
      - './secret/TWITTER_ACCESS_TOKEN_SECRET'
  - name: 'db-host'
    files:
      - './secret/DB_HOST'
  - name: 'db-username'
    files:
      - './secret/DB_USERNAME'
  - name: 'db-password'
    files:
      - './secret/DB_PASSWORD'
