---
resources:
  - './deployment-stable.yml'
  - './service-externalip.yml'
  - './ingress.yml'
  - './managed_certificate.yml'
  - './sealed_secret.yml'

configMapGenerator:
  - name: 'rails-env'
    literals:
      - 'RAILS_ENV=production'
      - 'RACK_ENV=production'
      - 'RAILS_SERVE_STATIC_FILES=1'
  - name: 'node-env'
    literals:
      - 'NODE_ENV=production'
