apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  selector:
    release: stable
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 34.107.172.230
status:
  loadBalancer:
    ingress:
    - ip: 34.107.172.230
