apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    release: stable
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.203.174.55
