apiVersion: v1
kind: Service
metadata:
  name: sports-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 10.128.0.15
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 8080
      targetPort: 3001
  selector:
    app: sports
